apps/agent/urls.py
from django.urls import path
from . import views


app_name='agent'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('register/phone_register/', views.phone_register, name='phone_register'),
    path('register/phone_verify/', views.phone_verify, name='phone_verify'),
    path('register/', views.AgentRegisterView.as_view(), name='register'),
    path('train_register/', views.AgentTrainView.as_view(), name='train_register'),
    # path('register/phone_verify', views.phone_verify, name='phone_verify'),
    # path('register/personal-info', views.SellerRegisterView.as_view(), name='personal-info'),
    # path('register/commer-info', views.SellerRegisterView.as_view(), name='commer-info'),
    # path('dashboard', views.SellerDashboardView.as_view(), name='dashboard'),
    # path('logout/', views.SellerLogoutView.as_view(), name='logout'),
    path('profile/', views.AgentProfileView.as_view(), name='profile'),
    path('tprofile/', views.AgentProfileView.as_view(), name='tprofile'),
    # path("register_ecco/", views.RegisterEccoInfoUserView.as_view(), name='register_ecco'),
    # path("select_production/", views.SelectCategoryView.as_view(), name='sellect_production'),
    # path("select_cat/", views.SelectCategoryView.as_view(), name='select_cat'),
    # path("add_dress/", views.AddDressView.as_view(), name='add_dress'),
    # path("add_equ/", views.AddEquipmentView.as_view(), name='add_equ'),
    # path("add_machin/", views.AddMachinView.as_view(), name='add_machin'),
    # path("list_production/", views.ListProductionView.as_view(), name='list_production'),
    # path("detail_production/<int:id>/", views.DetailProductionView.as_view(), name='detail_production'),
    # path("create_ticket/", views.OpenTicketView.as_view(), name='create_ticket'),
    # path("show_tickets/", views.ShowTicket.as_view(), name='show_tickets'),
    # path("detail_ticket/<int:id>/", views.DetailTicket.as_view(), name='detail_ticket'),
    # path("reply_ticket/<int:id>/", views.ReplyTicketView.as_view(), name='reply_ticket'),
]

cheestore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.seller.urls', namespace='seller')),
    path('', include('apps.agent.urls', namespace='agent')),
    path('accounts/', include('apps.accounts.urls', namespace= 'accounts')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/agent/forms.py
from dataclasses import fields
from msilib.schema import CheckBox
from random import choice
import re
from django import forms
from .models import AgentUser
from apps.accounts.models import CustomUser
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.shortcuts import render, redirect, get_object_or_404

class PhoneRegisterForm(forms.Form):
    phone_number = forms.CharField(label="", help_text="مثال: 09123456789",
                                    # widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'شماره تلفن همراه خود را وارد کنید'}),
                                    # error_messages={'required':'این فیلد الزامی است'},
                                    # validators=[RegexValidator(regex='^(09)\d{9}$',message="تلفن همراه می بایست 11رقم و فقط شامل عدد باشد  ",)]
                                    )


# class UserRegisterForm(forms.ModelForm):

#     class Meta:
#         model = CustomUser
#         fields = ('name', 'family', 'phone_number', 'national_code', 'email')

# class AgentRegisterForm(forms.ModelForm):
#     cv = forms.forms.FileField(label="آپلود رزومه",
#                                   required = False,
#                                   error_messages={'required':'این فیلد الزامی است'}
#                                    )

#     class Meta:
#         model = AgentUser
#         fields = ['phone','birth_year', 'residence_city', 'agency_city', 'job_history', 'last_collab', 'schooling', 'social_media_skills', 'job_space', 'reagent', 'familiarity_with_us', 'plunge_case', 'profational_skills', 'languages', 'favorites', 'cv']

#==================================================================================================================================================

    
class UserRegisterForm(forms.ModelForm):


    phone_number = forms.CharField(label='شماره همراه',
                                   validators=[RegexValidator(regex='^(09)\d{9}$',message="تلفن همراه می بایست 11رقم و فقط شامل عدد باشد  ",)],
                                   error_messages={'required':'این فیلد الزامی است'}
                                   )
    national_code = forms.CharField(label='کد ملی',
                                    validators=[RegexValidator(message="کد ملی می بایست 10رقم و فقط شامل عدد باشد  ",)],
                                    error_messages={'required':'این فیلد الزامی است'}
                                    )
    email = forms.EmailField(label='ایمیل',
                             error_messages={'required':'این فیلد الزامی است'}
                            )
    
    class Meta:
        model = CustomUser
        fields = ['name', 'family', 'phone_number', 'national_code', 'email']

class AgentRegisterForm(forms.ModelForm):
    
    # F_W_US = [
    #     ('google','جستجو در اینترنت'),
    #     ('instagram','اینستاگرام'),
    #     ('telegram','تلگرام'),
    #     ('friends','دوستان و آشنایان'),
    #     ('others','سایر')
    # ]
        
    # phone = forms.CharField(label='تلفن ثابت',
    #                         error_messages={'required':'این فیلد الزامی است'}
    #                         )
    # birth_year = forms.CharField(label='سال تولد',
    #                              error_messages={'required':'این فیلد الزامی است'}
    #                              )
    # residence_city = forms.CharField(label='شهر محل اقامت',
    #                                  error_messages={'required':'این فیلد الزامی است'}
    #                                  )
    # agency_city = forms.CharField(label='شهر مورد تقاضا یرای نمایندگی',
    #                               error_messages={'required':'این فیلد الزامی است'}
    #                               )
    # job_history = forms.CharField(label='سوابق شغلی',
    #                               error_messages={'required':'این فیلد الزامی است'}
    #                               )
    # last_collab = forms.CharField(label='مدت همکاری در آخرین تجربه کاری',
    #                               error_messages={'required':'این فیلد الزامی است'}
    #                               )
    # schooling = forms.CharField(label='میزان تحصیلات',
    #                             error_messages={'required':'این فیلد الزامی است'}
    #                             )
    # social_media_skills = forms.CharField(label='مهارت های فضای مجازی',
    #                                       error_messages={'required':'این فیلد الزامی است'}
    #                                       )
    # job_space = forms.CharField(label='متراژ و نوع فضای کار',
    #                             error_messages={'required':'این فیلد الزامی است'}
    #                             )
    # reagent = forms.CharField(label='معرف',
    #                           error_messages={'required':'این فیلد الزامی است'}
    #                           )
    # plunge_case = forms.CharField(label='وضعیت اشتغال',
    #                               error_messages={'required':'این فیلد الزامی است'}
    #                               )
    # profational_skills = forms.CharField(label='مهارت های حرفه ای',
    #                                      error_messages={'required':'این فیلد الزامی است'}
    #                                      )
    # languages = forms.CharField(label='میزان آشنایی شما با زبان انگلیسی و یا سایر زبان ها',
    #                             error_messages={'required':'این فیلد الزامی است'}
    #                             )
    # favorites = forms.CharField(label='مزایای شغلی مورد علاقه',
    #                         error_messages={'required':'این فیلد الزامی است'}
    #                         )
    # familiarity_with_us = forms.ChoiceField(label='چگونه با ما آشنا شدید؟انخاب کنید.',
    #                                       choices = F_W_US,
    #                                       error_messages={'required':'این فیلد الزامی است'}
    #                                       )
    
    cv = forms.forms.FileField(label="آپلود رزومه",
                                  required = False
                                )
    
    class Meta:
        model = AgentUser
        fields = ['phone','birth_year','residence_city','agency_city','job_history','last_collab','schooling',
                  'social_media_skills','job_space','reagent','plunge_case','profational_skills','languages',
                  'favorites','familiarity_with_us','cv']
        
class RuleForm(forms.Form):
    rule_accept = forms.BooleanField(label='قوانین و قرارداد فوق را مطالعه کرده و میپذیرم.',
                                     required= False)
    rule_deny = forms.BooleanField(label='عدم موافقت(در اینصورت حساب کاربری شما مسدود و به منزله قطع همکاری با چی استور تلقی میگردد)',
                                    required= False)
    later_read = forms.BooleanField(label='بعداَ مطالعه میکنم',
                                required= False)

apps/agent/views.py
from django.http import HttpResponse
from unicodedata import category
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.core.cache import cache
from django.urls import reverse

from apps.accounts.models import CustomUser

from .forms import (AgentRegisterForm, UserRegisterForm, RuleForm, PhoneRegisterForm)
from .models import AgentUser, Rule
from .utils import Send_sms
from django.contrib.auth import authenticate, login, logout
from django.views import View
import random
import logging
from azbankintro import iban_validate, IBANValidationException

class Home(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'agent/enter.html')
    
#=========================================AboutUs===========================================================
class About(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'about.html')
    
#=========================================CommonQuestions===========================================================
class CommonQuestions(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'common_q.html')
    
#=======================================PhoneRegister========================================================
# def codeGenerate():
#     return random.randint(1000,9999)
from django_otp.oath import totp

secret_key = b'12345678901234567890'
code = totp(key=secret_key, step=30, digits=4)

def phone_register(request):
    form = PhoneRegisterForm()
    if request.method == 'POST':
        form = PhoneRegisterForm(request.POST)
        if form.is_valid():
            opt = "reg"
            register_phone = form.cleaned_data['phone_number']
            Send_sms(register_phone,opt,code)
            #cache.set(register_phone,code,180)
            
        print(register_phone, ": " ,code)
        return redirect('agent:phone_verify')
        
    return render(request, 'agent/phone_register.html', {'form':form})

#============================PhoneVerify========================================================

def phone_verify(request):
    print("code", code)
    # register_phone = request.kwargs['register_phone'].value
    # print('register_phone',register_phone)
    # c_phone=cache.get(register_phone)
    # if request.method =='POST':
    verify_code = request.GET.get('phone_verify')
    if verify_code == str(code):
        print(verify_code, "You send to the next page")
        return redirect('agent:register')
    return render(request, 'agent/phone_verify.html',{'code':code})


#===================================================================================

class AgentRegisterView(View):
        
    def get(self,request, *args, **kwargs):
        user_form = UserRegisterForm()
        agent_form = AgentRegisterForm()
        return render(request, 'agent/register.html', {'user_form': user_form, 'agent_form':agent_form})

    def post(self,request,*args, **kwargs):
        user_form = UserRegisterForm()
        agent_form = AgentRegisterForm()
        if request.method == "POST":
            user_form = UserRegisterForm(request.POST)
            agent_form = AgentRegisterForm(request.POST, request.FILES or None)
            if user_form.is_valid() and agent_form.is_valid():
                custom_user = user_form.save()
                agent = agent_form.save(commit=False)
                agent.user = custom_user
                agent.save()
                messages.success(request,'ثبت اطلاعات با موفقیت انجام شد')
                return redirect('agent:profile')
            else:
                messages.error(request, 'اطلاعات وارد شده معتبر نمی باشد')
                return render(request, 'agent/register.html', {'user_form': user_form, 'agent_form': agent_form})
        
class AgentTrainView(View):
    def get(self, request, *args, **kwargs):
        user_form = UserRegisterForm()
        return render(request, 'agent/rt.html', {'user_form': user_form})
    
    def post(self, request, *args, **kwargs):
        
        user_form = UserRegisterForm()
        if request.method=='POST':
            user_form = UserRegisterForm(request.POST)
            if user_form.is_valid():
                name = user_form.cleaned_data.get('name')
                family = user_form.cleaned_data.get('family')
                phone_number = user_form.cleaned_data.get('phone_number')
                national_code = user_form.cleaned_data.get('national_code')
                email = user_form.cleaned_data.get('email')
                obj = CustomUser.objects.create(
                    name = name,
                    family = family,
                    phone_number = phone_number,
                    national_code = national_code,
                    email = email
                )
                obj.save()
                messages.success(request, 'ثبت اطلاعات با موفقیت انجام شد.')
                return redirect('agent:tprofile') 
            else:
                messages.error(request, 'اطلاعات وارد شده معتبر نمی باشد')
                return render(request, 'agent/rt.html', {'user_form': user_form}) 
        else:
            return render(request, 'agent/rt.html', {'user_form': user_form})  
        
class AgentProfileView(View):
    def get(self,request,*args, **kwargs):
        rule_form = RuleForm()
        return render(request, 'agent/profile.html',{'rule_form': rule_form})
    
    def post(self, request, *args, **kwargs):
        rule_form = RuleForm()
        if request.method == 'POST':
            rule_form = RuleForm(request.POST)
            if rule_form.is_valid():
                rule_accept = rule_form.cleaned_data.get('rule_accept')
                rule_deny = rule_form.cleaned_data.get('rule_deny')
                later_read = rule_form.cleaned_data.get('later_read')
                user = CustomUser.objects.all().last()
                obj = Rule.objects.create(
                    user = user,
                    rule_accept = rule_accept,
                    rule_deny = rule_deny,
                    later_read = later_read
                )
                obj.save()
                print(request.get_full_path)
                if request.path == "/profile/":
                    print('aaaaaaaaaaaaaaaaaaaaaa',request.get_full_path)
                    return redirect('go-to-gateway') 
                else:
                    return redirect('t-go-to-gateway')
            else:
                messages.error(request, 'اطلاعات وارد شده معتبر نمی باشد')
                return render(request, 'agent/profile.html', {'rule_form': rule_form}) 
        else:
            return render(request, 'agent/profile.html', {'rule_form': rule_form}) 
                
                       

    # def post(self,request,*args, **kwargs):
    #     return redirect('agent:login')

templates/agent/enter.html
{% extends 'main.html' %}
{% load static %}

{% block title %}ورود{% endblock title %}


{% block content %}
{% comment %} <iframe src="https://iframe.enama.ir/player/3573305" allowFullScreen="true" scrolling="no" webkitallowfullscreen="true" mozallowfullscreen="true" style="width: 100%; height: 100%"></iframe> {% endcomment %}
{% comment %} <h1 class="text-center text">سامانه ثبت نام نمایندگان پوشاک ایران</h1> {% endcomment %}
<div id="3573305" datakey="3573305">
    <script type="text/JavaScript" src="https://api.enama.ir/Object/embeded/3573305">
    </script>
</div>
<br>
<br>

<button type="button" class="button"><a href="{% url 'agent:register' %}" alt='Broken Link'>ثبت نام متقاضیان اخذ نمایندگی</a></button>
<button type="button" class="button"><a href="{% url 'agent:train_register' %}" alt='Broken Link'>ثبت نام متقاضیان دوره آموزش نمایندگی</a></button>
<p style="text-align:center;" width="720px"><img src="{% static 'css/logo/chee.jpg' %}" width="120" height="120" alt="centered image"></p>
{% comment %} <a referrerpolicy="origin" target="_blank" href="https://trustseal.enamad.ir/?id=248366&amp;Code=nWHbJZwi5ZetplLy6fZO"><img referrerpolicy="origin" src="https://Trustseal.eNamad.ir/logo.aspx?id=248366&amp;Code=nWHbJZwi5ZetplLy6fZO" alt="" style="cursor:pointer" id="nWHbJZwi5ZetplLy6fZO"></a> {% endcomment %}
{% comment %} <a href="{% url 'agent:register' %}"><input type="submit" value="ثبت نام" class="btn btn-success"></a> {% endcomment %}

{% endblock content %}

templates/agent/phone_register.html
{% extends 'main.html' %}

{% block title %}ثبت تلفن همراه{% endblock title %}ثبت تلفن همراه

{% block content %}
<h1 class="text-center" style="color:white">ثبت تلفن همراه</h1>
<div class="container" style="color:white">
    <div class="row justify-content-center align-items-center">
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <div>
        <input type="submit" class="btn btn-primary mt-3" value="تایید">
        </div>
    </form>
    </div>
</div>
{% endblock content %}

templates/agent/phone_verify.html
{% extends 'main.html' %}

{% block title %}تایید تلفن همراه{% endblock title %}
{% block content %}

<h3>{{message}}</h3>

<p style="color:white">لطفا کد ارسال شده را وارد کنید</p>
<form action="" >
    {% csrf_token %}
    <div class="form-group mt-2" style="color:white">
        <label for="phone_verify">کد تایید : </label>
        <input type="number" name="phone_verify" id="phone_verify">
    </div>
    <div class= "mt-2">
        <input type="submit" class="btn btn-primary" value="ارسال">
    </div>
</form>
<div class= "mt-4" style="color:white">
    <p>کدی دریافت نکرده اید؟<a href="#">ارسال مجدد کد</a></p>
    
</div>
<div class= "mt-2">
    <p><a href="">ویرایش شماره تلفن</a></p>
</div>

<p style="color:white">{{code}}</p>

        
{% endblock content %}

templates/agent/profile.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}

{% block title %}ثبت نام فروشندگان{% endblock title %}

{% block content %}
<h1 style="color:white">پذیرش قرارداد</h1>


<form action="" method="post" style="color:white">
    {% csrf_token %}

    <textarea class= "container-fluid mt-auto" dir='rtl' name="rule" id="rule" cols="50" rows="10" style="overflow:auto;">
        قوانین و قرارداد
        ین قرارداد شامل عقد از راه دور بوده و ایجاب و قبول آن با استفاده از وسایل ارتباط از راه دور است که شخص ثبت نام کننده آنرا بدون هیچ گونه اجبار و اکراه و از روی صحت و سالمت و رضایت کامل بوسیله امضای الکترونیک و فشار دادن دکمه تایید مطابق ماده 10 قانون مدنی و وفق ماده 2 و 7 قانون تجارت الکترونیک این قرارداد را منعقد و امضاء نموده است که صیغۀ بیع شرعی و قانونی بدینوسیله بین طرفین جاری می گردد.
        روي صحت و سلامت و رضايت کامل اين قرار داد را منعقد نموده است .
        ارسال شده میباشد و موظف به اطلاع رسانی قبولی یا رد رزومه کاری ارسال شده توسط متقاضی است خریدار می باشد .
        این قرارداد هیچگونه تعهد استخدامی برای چی استور ایجاد نمیکند و از شمول قانون کار و بیمه خارج است و صرفاً جهت بررسی رزومه کاری متقاضیان محترم می باشد .
        هر شخص می باید مستقیما در سایت رسمی شرکت با نام خود ثبت نام کند و مسئولیت هر گونه عدم تطابق اطلاعات ذکر شده در رزومه به عهده نامبرده (متقاضی) می‌باشد.
         طبق ماده 555 قانون مجازات اسلامی  هر گونه جعل عنوان ممنوع بوده و مسئولیت استفاده از عناوین کذب به عهده متقاضی می‌باشد .
        ماده2 تجارت الکترونيکي
        (امضاي الکترونيکي) (Electronic Signature):
        عبارت از هر نوع علامت منضمم شده يا به نحو منطقي متصل شده به(داده پيام) است كه براي شناسايي امضاء كننده(داده پيام)، مورد استفاده قرار مي گيرد.
        (وسایل ارتباط ازراه دور)(Means Of Distance Communication):
        عبارت از هر نوع وسيله اي است كه بدون حضور فيزيكي همزمان تامين كننده و مصرف كننده جهت فروش كالا و خدمات استفاده مي‌شود.
        (عقدازراه دور)(Distance Contract):
        ايجاب و قبول راجع به كالاها و خدمات بين تامين كننده و مصرف كننده با استفاده از وسايل ارتباط از راه دور است.
        ماده 7 تجارت الکترونيکي:
        هر گاه قانون وجود امضاء را لازم بداند امضاي الکترونيکي مكفي است.
        ماده 10 مدني :
        قراردادهاي خصوصي نسبت به کسانيکه آن را منعقد نموده اند درصورتي که مخالف صريح قانون نباشد نافذ است.
        اين قرار داد وفق ماده 2 و 7 قانون تجارت الکترونيک و ماده 10 قانون مدني جمهوري اسلامي ايران منعقد گرديد و بين طرفين لازم مي باشد.
    </textarea>

    {{ rule_form | crispy }}
 
    <button>پرداخت آنلاین</button>

</form>

{% endblock content %}

  

templates/agent/register.html
{% extends 'main.html' %}

{% load crispy_forms_tags %}

{% block title %}صفحه ثبت نام نمایندگان{% endblock title %}


{% block content %}
<h1 class="text-center" style="color:white">ثبت نام متقاضیان اخذ نمایندگی</h1>
<br>

<div class="row justify-content-md-center form-group" style="color:white">  
    <form enctype="multipart/form-data" action="" method="post">
        {% csrf_token %}
        {{ user_form | crispy }}
        {{ agent_form | crispy }}
        <br>
        <button>ثبت اطلاعات</button>
    </form>
</div>
{% endblock content %}

templates/agent/rt.html
{% extends 'main.html' %}

{% load crispy_forms_tags %}

{% block title %} ثبت نام متقاضیان دوره{% endblock title %}


{% block content %}
<h1 class="text-center" style="color:white">ثبت نام متقاضیان دوره آموزش نمایندگی</h1>
<br>
<!-- Start Reservation -->
<div class="reservation-box">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-sm-12 col-xs-12">
                <div class="contact-block">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <input type="text" class="form-control" id="name" name="name" placeholder="نام" required data-error="Please enter your name">
                                        <div class="help-block with-errors"></div>
                                    </div>                                 
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <input type="text" class="form-control" id="national_code" name="national_code" placeholder="کد ملی" required data-error="Please enter your name">
                                        <div class="help-block with-errors"></div>
                                    </div>                                 
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <input type="text" class="form-control" id="phone_number" name="phone_number" placeholder="شماره همراه" required data-error="Please enter your name">
                                        <div class="help-block with-errors"></div>
                                    </div>                                 
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <input type="text" class="form-control" id="family" name="family" placeholder="نام خانوادگی" required data-error="Please enter your name">
                                        <div class="help-block with-errors"></div>
                                    </div>                                 
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <input type="text" placeholder="ایمیل" id="email" class="form-control" name="email" required data-error="Please enter your email">
                                        <div class="help-block with-errors"></div>
                                    </div> 
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <input type="text" placeholder="سال تولد" id="phone" class="form-control" name="phone" required data-error="Please enter your Numbar">
                                        <div class="help-block with-errors"></div>
                                    </div> 
                                </div>
                                {% comment %} <div class="col-md-12">
                                    <div class="form-group">
                                            <input type="text" placeholder="شهر مورد تقاضا برای نمایندگی" id="agency_city" class="form-control" name="agency_city" required data-error="Please enter your Numbar">
                                            <div class="help-block with-errors"></div> 
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <input type="text" placeholder="میزان تحصیلات" id="schooling" class="form-control" name="schooling" required data-error="Please enter your Numbar">
                                        <div class="help-block with-errors"></div>
                                    </div> 
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <input type="text" class="form-control" id="last_collab" name="last_collab" placeholder="مدت همکاری در آخرین تجربه شغلی" required data-error="Please enter your name">
                                        <div class="help-block with-errors"></div>
                                    </div>                                 
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <input type="text" class="form-control" id="perfational_skills" name="perfational_skills" placeholder="مهارت های حرفه ای" required data-error="Please enter your name">
                                        <div class="help-block with-errors"></div>
                                    </div>                                 
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <input type="text" class="form-control" id="plunge_case" name="plunge_case" placeholder="وضعیت اشتغال" required data-error="Please enter your name">
                                        <div class="help-block with-errors"></div>
                                    </div>                                 
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <input type="text" class="form-control" id="favorites" name="favorites" placeholder="مزایای مورد علاقه شما" required data-error="Please enter your name">
                                        <div class="help-block with-errors"></div>
                                    </div>                                 
                                </div>                                
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <select class="custom-select d-block form-control" name="familiarity_with_us" id="familiarity_with_us" required data-error="Please select Person">
                                            <option disabled selected>چگونه با ما آشنا شدید؟انتخاب کنید</option>
                                            <option value="1">جستجو در اینترنت</option>
                                            <option value="2">اینستاگرام</option>
                                            <option value="3">تلگرام</option>
                                            <option value="4">دوستان و آشنایان</option>
                                            <option value="5">سایر</option>
                                        </select>
                                        <div class="help-block with-errors"></div>
                                    </div> 
                                </div> {% endcomment %}
                            </div>
                        </div>   
                        <br>
                        <br>
                        <button class="text-center">ثبت اطلاعات</button>          
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>


{% endblock content %}
    
    
    
    

templates/agent/success_payment.html
{% extends 'main.html' %}
{% load static %}

{% block title %}تکمیل ثبت نام{% endblock title %}


{% block content %}
<h1 style="color:white">پرداخت شما با موفقیت انجام شد.</h1>
<h2 style="color:white">به چی استور خوش آمدید.</h2>
{% endblock content %}

templates/agent/t_success_payment.html
{% extends 'main.html' %}
{% load static %}

{% block title %}تکمیل ثبت نام{% endblock title %}


{% block content %}
<h1 style="color:white">پرداخت شما با موفقیت انجام شد.</h1>
<h2 style="color:white">اطلاعات مربوط به دوره برای شما پیامک میگردد.</h2>
{% endblock content %}