apps/marketer/urls.py
from django.urls import path
from . import views


app_name='marketer'
urlpatterns = [
    path('marketer/', views.MarketerLoginView.as_view(), name='login'),
    path('marketer/register/', views.MarketerApplicationView.as_view(), name='register'),
    path('marketer/logout/', views.MarketerLogoutView.as_view(), name='logout'),
    path('marketer/profile/', views.MarketerProfileView.as_view(), name='profile'),
    path('marketer/update_profile/', views.MarketerUpdateProfileView.as_view(), name='update_profile'),
    path('marketer/change_password/', views.ChangePasswordView.as_view(), name='change_password'),
]
    
    

apps/wallet/urls.py
from django.urls import path
from . import views

app_name="wallet"
urlpatterns = [    
    path("webhooks/wallets_africa/aDshFhJjmIalgxCmXSj/", views.webhook, name = "webhook"),
    path("create/", views.create_wallet, name="create_wallet")
    ]

cheestore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.seller.urls', namespace='seller')),
    path('', include('apps.agent.urls', namespace='agent')),
    path('accounts/', include('apps.accounts.urls', namespace= 'accounts')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/marketer/models.py
from django.db import models
from apps.accounts.models import CustomUser



gender_choices=(('M','مرد'),('F','زن'))


class ProfileMrketer(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='marketer')
    password= models.CharField(max_length=32, blank=True, null=True)
    birthdate = models.DateTimeField(verbose_name='تولد', blank=True, null=True)
    gender = models.CharField(verbose_name='جنسیت', choices = gender_choices, max_length=8, blank=True, null=True)
    id_number = models.CharField(verbose_name='شماره شناسنامه', max_length=10, unique=True)
    Nationality = models.CharField(verbose_name='ملیت', max_length=64, null=True, blank=True)
    Religion = models.CharField(verbose_name='مذهب', max_length=64, null=True, blank=True)
    father_name = models.CharField(verbose_name='نام پدر',max_length=64, null=True, blank=True)
    city = models.CharField(verbose_name='شهر', max_length=64, null=True, blank=True)
    address = models.CharField(verbose_name='ادرس محل سکونت', max_length=512, null=True, blank=True)
    zip_code= models.CharField(verbose_name='کدپستی', max_length=10, null=True, blank=False, default='')
    representative = models.CharField(verbose_name='معرف', max_length=256, null=True, blank=True) # 3 peaple and their phone number
    cv = models.FileField(verbose_name='آپلود رزومه',upload_to='resume/', null=True, blank=True)
    personal_image= models.ImageField(verbose_name='عکس پرسنلی',upload_to='upload_document_image_path', null=True, blank=True)
    work_experience = models.CharField(verbose_name='سوابق شغلی', max_length=256, null=True, blank=True)
    Familiarity_socialmedia = models.CharField(verbose_name='میزان آشنایی با فضای مجازی ', max_length=512, null=True, blank=True)   
    Familiarity_Language = models.CharField(verbose_name='آشنایی با زبان خارجی', max_length=512, null=True, blank=True)
    Familiarity_Marketing = models.CharField(verbose_name='آشنایی با متد های روز تبلیغات و بازاریابی', max_length=512 , null=True, blank=True)
    Familiarity_IT = models.CharField(verbose_name='میزان آشنایی با کامپیوتر', max_length=256, null=True, blank=True)   
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default= False)


    def __str__(self):
        return self.address
    
    class Meta:
        verbose_name = 'نماینده'
        verbose_name_plural = 'نماینده ها '







       

     

apps/marketer/forms.py
from django import forms
from accounts.models import CustomUser
from .models import ProfileMrketer 
from django.core.exceptions import ValidationError


###########################################################################################################################################################################################

class ApplicationForm(forms.ModelForm):

    phone_number = forms.CharField(max_length=255, label="تلفن همراه",
                                   widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'شماره تلفن همراه خود را وارد کنید'}),
                                   error_messages={'required':'این فیلد الزامی است'}
                                   )
    name = forms.CharField(max_length=150, widget=forms.Textarea, label='نام')
    family = forms.CharField(max_length=255, widget=forms.Textarea, label='نام خانوادگی')
    national_code = forms.CharField(max_length=255, widget=forms.Textarea, label='کدملی')
    email = forms.EmailField(max_length=255, widget=forms.Textarea, label='ایمیل')
    password= forms.CharField(max_length=32,label="رمز عبور",
                                   widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'رمز عبور را وارد کنید'}),
                                   error_messages={'required':'این فیلد الزامی است'}
                                   )
    birthdate = forms.DateTimeField(label='تاریخ تولد',
                                widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'تاریخ تولد خود را وارد کنید', 'type':'date'}),
                                error_messages={'required':'این فیلد الزامی است'}
                                )
    id_number = forms.CharField(max_length=10,label='تاریخ تولد',
                                widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'شماره شناسنامه  خود را وارد کنید'}),
                                error_messages={'required':'این فیلد الزامی است'})
    Nationality = forms.CharField(max_length=64, widget=forms.Textarea, label='ملیت')
    Religion = forms.CharField(max_length=64, widget=forms.Textarea, label='مذهب')
    father_name = forms.CharField(max_length=64, widget=forms.Textarea, label='نام پدر')
    city = forms.CharField(max_length=64, widget=forms.Textarea, label='شهر')
    address = forms.CharField(max_length=512, label='تاریخ تولد',
                                widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'آدرس  خود را وارد کنید'}),
                                error_messages={'required':'این فیلد الزامی است'})
    zip_code= forms.CharField(max_length=10, widget=forms.Textarea, label='کد پستی')
    representative = forms.CharField(max_length=256, widget=forms.Textarea, label=' معرف') # 3 peaple and their phone number
    work_experience = forms.CharField(max_length=256, widget=forms.Textarea, label='تجربیات کاری')
    Familiarity_socialmedia = forms.CharField(max_length=512, widget=forms.Textarea, label='میزان آشنایی با فضای مجازی')   
    Familiarity_Language = forms.CharField(max_length=512, widget=forms.Textarea, label=' آشنایی با زبان خارجی')
    Familiarity_Marketing = forms.CharField(max_length=512, widget=forms.Textarea, label='میزان آشنایی با متد های روز بازاریابی و تبلیغات')
    Familiarity_IT = forms.CharField(max_length=256, widget=forms.Textarea, label='آشنایی با کامپیوتر')


    
    class Meta:
            model = ProfileMrketer
            fields = ['personal_image','gender','cv']




###########################################################################################################################################################################################

class UserRegisterForm(forms.ModelForm):
    password1 = forms.CharField(label='رمز عبور',widget=forms.PasswordInput)
    password2 = forms.CharField(label='تکرار رمز عبور',widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ('name', 'family', 'phone_number', 'national_code', 'email', 'password1', 'password2')


    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("رمز عبور مطابقت ندارد")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

###########################################################################################################################################################################################

class MarketerLoginForm(forms.ModelForm):
    national_code = forms.CharField(label="کدملی",
                                   widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'شماره کدملی خود را وارد کنید'}),
                                   error_messages={'required':'این فیلد الزامی است'}
                                   )
    password = forms.CharField(label="رمز عبور",
                                   widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'رمز عبور را وارد کنید'}),
                                   error_messages={'required':'این فیلد الزامی است'}
                                   )

###########################################################################################################################################################################################

class UserProfileForm(forms.ModelForm):

    class Meta:
        model = CustomUser
        fields = ('name', 'family', 'phone_number', 'national_code', 'email')

apps/marketer/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import ProfileMrketer
from accounts.models import CustomUser
from .forms import ApplicationForm,MarketerLoginForm, UserRegisterForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views import View
import random


#=================================MarketerLogin===================================================

class MarketerLoginView(View):

    
    def get(self,request, *args, **kwargs):
        form = MarketerLoginForm()
        return render(request,'marketer.html', {'form':form})

    def post(self,request,*args, **kwargs):
        form = MarketerLoginForm(request.POST)
        if form.is_valid():
            username=form.cleaned_data.get('national_code')
            password=form.cleaned_data.get('password')
            user = authenticate(
            username=username,
            password=password
            )
            x = ProfileMrketer.objects.get('is_active')
            if x is True and user is not None:
                messages.success(request,'خوش آمدید')
                login(request,user)
                next_url=request.GET.get('next')
                if next_url is not None:
                    return redirect(next_url)

                return redirect('marketer:profile')

            else:
                messages.warning(request,'کاربر با این مشخصات یافت نشد')
                return render(request, 'marketer.html', {'form':form})
        else:
            messages.error(request, 'اطلاعات وارد شده معتبر نمی باشد')
            return render(request, 'marketer.html', {'form':form})

#============================MarketerLogout========================================================

class MarketerLogoutView(View):    
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('marketer:login')
        return super().dispatch(request, *args, **kwargs)
    
    def get(self,request, *args, **kwargs):
        logout(request)
        messages.warning(request, 'خروج شما با موفقیت انجام شد')
        return redirect('marketer:login')

#=================================MarketerRegister===================================================

class MarketerApplicationView(View):
    def get(self,request, *args, **kwargs):
        user_form = UserRegisterForm()
        marketer_form = ApplicationForm()
        return render(request, 'marketer/register.html', {'user_form': user_form, 'marketer_form':marketer_form})

    def post(self,request,*args, **kwargs):
        user_form = UserRegisterForm(request.POST)
        marketer_form = ApplicationForm(request.POST, request.FILES)
        if user_form.is_valid() and marketer_form.is_valid():
            custom_user = user_form.save()
            marketer = marketer_form.save(commit=False)
            marketer.user = custom_user
            marketer.save()
            messages.success(request,'ثبت نام با موفقیت انجام شد')
            return redirect('marketer:login')
        else:
            messages.error(request, 'اطلاعات وارد شده معتبر نمی باشد')
            return render(request, 'marketer/register.html', {'user_form': user_form, 'marketer_form': marketer_form})

#=============================MarketerProfile=======================================================

class MarketerProfileView(View):
    def get(self,request,*args, **kwargs):
        user=request.user
        marketer=ProfileMrketer.objects.get(user=user)
        return render(request, 'marketer/profile.html', {'user':user, 'marketer':marketer})


#=============================MarketerUpdateProfile=======================================================

class MarketerUpdateProfileView(View):
    def get(self,request,*args, **kwargs):
        user_form = ApplicationForm(instance=request.user)
        return render(request, 'marketer/update_profile.html',{'user_form':user_form})

    def post(self,request,*args, **kwargs):
        user_form = UserProfileForm(request.POST, instance=request.user)
        if user_form.is_valid():
            user_form.save()
            messages.success(request, 'پروفایل شما با موفقیت ویرایش شد')
            return redirect('marketer:profile')
        else:
            messages.error(request, 'اطلاعات وارد شده معتبر نمی باشد')
            return render(request, 'marketer/update_profile.html', {'user_form': user_form})

#=============================ChangePassword=======================================================


from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin

class ChangePasswordView(SuccessMessageMixin, PasswordChangeView):
    template_name = 'marketer/change_password.html'
    success_message = "رمز عبور با موفقیت تغییر کرد"
    success_url = reverse_lazy('marketer:Profilemarketer')

templates/marketer/change_password.html
{% extends "main.html" %}

{% block titile %}تغییر رمز عبور{% endblock titile %}

{% block content %}

    {% if form.errors %}
                {% for error in form.errors %}
                    <strong>{{ error }}</strong>
                {% endfor %}
    {% endif %}


        <form action="{% url 'marketer:change_password' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="old_password">رمز عبور قدیمی</label>
                <input type="password" name="old_password" class="form-control" required/>
            </div>
            <div class="form-group">
                <label for="new_password1">رمز عور جدید</label>
                <input type="password" name="new_password1" class="form-control" required/>
            </div>
            <div class="form-group">
                <label for="new_password2">تکرار رمز عبور جدید</label>
                <input type="password" name="new_password2" required class="form-control"/>
            </div>
            <div class="mt-1">
                <button type="submit" class="btn btn-success">تایید</button>
            </div>
        </form>

{% endblock content %}

templates/marketer/login.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}

{% block title %}صفحه ورود نمایندگان{% endblock title %}




{% block content %}
    <h1 class="text-center text-primary">ورود فروشندگان</h1>
    <div class="row justify-content-md-center m-5">
        <form action="marketer" method="post">
            {% csrf_token %}
            {{ form | crispy }}
            <input type="submit" value="ورود" class='btn btn-success btn-lg'>
        </form>
    </div>
    <div class="m-5">
        <p><a href="/accounts/password_reset/">رمز عبورم را فراموش کرده ام</a></p>
    </div>
    
    
    <div class="m-5">
        <p>هنوز ثبت نام کرده اید؟<a href="{% url ''marketer:regester'' %}">همین حالا ثبت نام کنید</a></p>
        
    </div>
{% endblock content %}

templates/marketer/marketer_profile.html
{% extends 'main.html' %}

{% block title %}پروفایل {{user}}{% endblock title %}


{% block content %}

<img src="{{marketer.personal_image.url}}" alt="{{marketer.user}}">
<div>
    <h2>اطلاعت شخصی :</h2>
    <hr>
    <p>نام : {{user.name}}
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    نام خانوادگی : {{user.family}}
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    تلفن همراه : {{user.phone_number}}</p>
    <p>
    کدملی : {{user.national_code}}
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    آدرس ایمیل : {{user.email}}
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    جنسیت : {{marketer.gender}}
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
   </p>
    <p>
    آدرس : {{marketer.address}}
    </p>
</div>
<br>
    <hr>
<br>
<div>
        <h2>اطلاعات نماینده :</h2>
        <hr>
        <p>کد پستی : {{user.zip_code}}
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        تلفن همراه : {{user.phone_number}}</p>
        <p>
        شماره شناسنامه : {{user.id_number}}
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        جنسیت : {{marketer.gender}}
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        تاریخ تولد : {{seller.birthdate}}</p>
        <p>
        آدرس : {{marketer.address}}
        </p>
</div>

<a class="btn btn-danger btn-lg mt-4" href="{% url 'marketer:update_profile' %}">ویرایش اطلاعات</a>

{% endblock content %}

templates/marketer/profile.html
{% extends 'main.html' %}

{% block title %}{% endblock title %}

{% block content %}
    <div class="row justify-content-between">
        <div class="col-3">
            <a class="btn btn-outline-info btn-lg" href="{% url 'marketer:profile' %}">پروفایل<i class="user icon"></i></a>
        </div>
        <div class="col-3">
            <a class="btn btn-outline-info btn-lg" href="{% url 'wallet:create_wallet' %}">کیف پول<i class="money icon"></i></a>            
        </div>
        <div class="col-3">
            <a class="btn btn-outline-info btn-lg" href="">تیکت</a>           
        </div>
        <div class="col-3">
            <a class="btn btn-outline-info btn-lg" href="">اضافه کردن محصول</a>            
        </div>
    </div>

    <h1>{{user}} به پنل کاربری خوش آمدید</h1>
{% endblock content %}

templates/marketer/register.html
{% extends 'main.html' %}

{% load crispy_forms_tags %}

{% block title %}صفحه ثبت نام نمایندگان{% endblock title %}


{% block content %}
<h1 class="text-center text-primary">ثبت نام فروشندگان</h1>
<div class="row justify-content-md-center form-group">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form | crispy }}
        {{ marketer_form | crispy }}
        <input type="submit" value="ثبت نام" class="btn btn-success">
    </form>
</div>
{% endblock content %}

templates/marketer/update_profile.html
{% extends 'main.html' %}

{% block title %}صفحه ویرایش پروفایل {{user}}{% endblock title %}

{% block content %}
<h1>ویرایش پروفایل<h1>


<form action="marketer" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
    {{user_form.as_p}}
    {{marketer_form.as_p}}
    <div class="form-group">
        <a href="{% url 'marketer:change_password' %}">تغییر رمز عبور</a>
    </div>
    <input type="submit"  class='btn btn-success btn-lg' value="ذخیره">
    </div>
</form>

{% endblock content %}

  