apps/agent/urls.py
from django.urls import path
from . import views


app_name='agent'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('register/phone_register/', views.phone_register, name='phone_register'),
    path('register/phone_verify/', views.phone_verify, name='phone_verify'),
    path('register/', views.AgentRegisterView.as_view(), name='register'),
    path('train_register/', views.AgentTrainView.as_view(), name='train_register'),
    # path('register/phone_verify', views.phone_verify, name='phone_verify'),
    # path('register/personal-info', views.SellerRegisterView.as_view(), name='personal-info'),
    # path('register/commer-info', views.SellerRegisterView.as_view(), name='commer-info'),
    # path('dashboard', views.SellerDashboardView.as_view(), name='dashboard'),
    # path('logout/', views.SellerLogoutView.as_view(), name='logout'),
    path('profile/', views.AgentProfileView.as_view(), name='profile'),
    path('tprofile/', views.AgentProfileView.as_view(), name='tprofile'),
    # path("register_ecco/", views.RegisterEccoInfoUserView.as_view(), name='register_ecco'),
    # path("select_production/", views.SelectCategoryView.as_view(), name='sellect_production'),
    # path("select_cat/", views.SelectCategoryView.as_view(), name='select_cat'),
    # path("add_dress/", views.AddDressView.as_view(), name='add_dress'),
    # path("add_equ/", views.AddEquipmentView.as_view(), name='add_equ'),
    # path("add_machin/", views.AddMachinView.as_view(), name='add_machin'),
    # path("list_production/", views.ListProductionView.as_view(), name='list_production'),
    # path("detail_production/<int:id>/", views.DetailProductionView.as_view(), name='detail_production'),
    # path("create_ticket/", views.OpenTicketView.as_view(), name='create_ticket'),
    # path("show_tickets/", views.ShowTicket.as_view(), name='show_tickets'),
    # path("detail_ticket/<int:id>/", views.DetailTicket.as_view(), name='detail_ticket'),
    # path("reply_ticket/<int:id>/", views.ReplyTicketView.as_view(), name='reply_ticket'),
]

apps/store/urls.py
from django.urls import path
from . import views


app_name='store'
urlpatterns = [
    path('', views.StoreLoginView.as_view(), name='login'),
    path('register/', views.StoreRegisterView.as_view(), name='register'),
    path('register/phone_register/', views.phone_register, name='phone_register'),
    path('register/phone_verify/', views.phone_verify, name='phone_verify'),
    path('register/personal-info/', views.StoreRegisterView.as_view(), name='personal-info'),
    path('register/commer-info/', views.StoreRegisterView.as_view(), name='commer-info'),
    path('dashboard/', views.StoreDashboardView.as_view(), name='dashboard'),
    path('logout/', views.StoreLogoutView.as_view(), name='logout'),
    path('profile/', views.StoreProfileView.as_view(), name='profile'),
    path('update_profile/', views.StoreUpdateProfileView.as_view(), name='update_profile'),
    path('change_password/', views.ChangePasswordView.as_view(), name='change_password'),
]

cheestore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.seller.urls', namespace='seller')),
    path('', include('apps.agent.urls', namespace='agent')),
    path('accounts/', include('apps.accounts.urls', namespace= 'accounts')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/carousel.html
  <div id="carouselExampleIndicators" class="carousel slide container" data-bs-ride="true">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{{MEDIA_URL}}/images/carousel/666-450x300.jpg" class=" d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="{{MEDIA_URL}}/images/carousel/443-450x300.jpg" class=" d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="{{MEDIA_URL}}/images/carousel/431-450x300.jpg" class=" d-block w-100" alt="...">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

templates/partials/footer.html
{% load static %}

<footer class = "footer mt-auto py-3 bg-dark" >
    <div class="container">
      <div class="row">
        <div class="col" >
          <a href="{% static 'logo/enamad.html' %}" target="_blank"><img src="{% static 'logo/enamad.jpg' %}"></a>
          <a href="{% url 'about' %}">درباره ما | </a>
          <a href="{% url 'common_questions' %}">سوالات متداول</a>

        </div>
      </div>
      
      <span style="color: #fff;">
          <p>تمامی حقوق این سایت متعلق به شرکت لیان یاقوت ممتاز ایده (لیما) می باشد</p>
          <p>&copy; تابستان 1401</p>
      </span>
    </div>
</footer>

templates/partials/index.html
{% extends 'main.html' %}

{% block title %}صفحه ثبت نام فروشندگان{% endblock title %}



{% block content %}
<h1>سامانه فروش تولیدکنندگان پوشاک کشور</h1>

<div class="seller-login-form">
    <form action="{% url 'accounts:login' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="phone_number"><strong>تلفن همراه:</strong></label>
                <div class="ui left icon input">
                    <input type="text" placeholder='تلفن همراه خود را وارد کنید' class="form-control">
                    <i class="user icon"></i>
                </div>
            </div>
            <div class ="form-group">
                <label for="password"><strong>رمز عبور:</strong></label>
                <div class="ui left icon input">
                    <input type="password" placeholder="رمز عبور" class="form-control">
                    <i class="key icon"></i>
                </div>
            </div>
        <input class="btn btn-lg btn-success m-2" type="submit" value="ورود" class="form-control">
        <div class="checkbox my-1 mr-sm-2">
            <input type="checkbox" name= "remember_me" id="remember_me">
            <label for="remember_me">مرا به خاطر بسپار</label>
        </div>
        <div class="my-4">
            <p>هنوز ثبت نام کرده اید؟<a href="{% url 'accounts:register' %}">همین حالا ثبت نام کنید</a></p>
        </div>
    </form>
</div>


{% comment %} <h1>به صفحه فروشندگان چی استور خوش آمدید</h1>


<div class="m-auto">
<form action="{% url 'accounts:login' %}" method="post" id="login-form" >
    {% csrf_token %}
    <div class= "mt-2">
        <label for="phone_number">تلفن همراه :</label>
        <input name='phone_number' placeholder='تلفن همراه خود را وارد کنید' maxlength='255' autocomplete='email' required>
    </div>
               
    <div class= "mt-2">
        <label for="password">رمز عبور :</label>
        <input name='password' type='password' placeholder='رمز عبور خود را وارد کنید' minlength='4' maxlength='255' autocomplete='current-password' required>
    </div>

    <div class= "mt-2">
        <input class ="btn btn-success" type="submit" value="ورود">
        <input type="hidden" name="next" value="{{ next }}"> 
    </div>          
</form>
</div>

<div>
    <p><a href="">رمز عبورم را فراموش کرده ام</a></p>
</div>


<div>
    <p>هنوز ثبت نام کرده اید؟<a href="{% url 'accounts:register' %}">همین حالا ثبت نام کنید</a></p>
    
</div>
   {% endcomment %}

{% endblock content %}

templates/partials/messages.html
{% if messages %}
    {% for message in messages %}
        <h3 {% if message.tags %}  class="alert alert-{{message.tags}}">{% endif %}{{message}}</h3>
    {% endfor %}
{% endif %}





{% comment %} {% if messages %}
    {% for message in messages %}
        {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}
    {% endfor %}
{% endif %} {% endcomment %}

templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'seller:login' %}">صفحه اصلی</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">تولید کنندگان</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            محصولات
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">مردانه</a></li>
            <li><a class="dropdown-item" href="#">زنانه</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">بچه گانه</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <ul class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
      <li class="nav-item active">
        <a class="nav-link" href="#"<p>{{user}}</p></a>
      </li>        
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'seller:logout' %}">خروج</a>
        </li>  
        {% else %}

        <li class="nav-item active">
          <a class="nav-link" href="{% url 'seller:login' %}">ورود</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'seller:phone_register' %}">ثبت نام</a>
        </li> 
        {% endif %}      
    </ul>
  </div>
</nav>

templates/partials/script.html
<script>
    $(document).ready(function() {
        $("#datepicker").datepicker();
    });
</script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>