apps/seller/urls.py
from django.urls import path
from . import views


app_name='seller'
urlpatterns = [
    path('', views.SellerLoginView.as_view(), name='login'),
    path('register/', views.SellerRegisterView.as_view(), name='register'),
    path('register/phone_register', views.phone_register, name='phone_register'),
    path('register/phone_verify', views.phone_verify, name='phone_verify'),
    path('register/personal-info', views.SellerRegisterView.as_view(), name='personal-info'),
    path('register/commer-info', views.SellerRegisterView.as_view(), name='commer-info'),
    path('dashboard', views.SellerDashboardView.as_view(), name='dashboard'),
    path('logout/', views.SellerLogoutView.as_view(), name='logout'),
    path('profile/', views.SellerProfileView.as_view(), name='profile'),
    path("register_ecco/", views.RegisterEccoInfoUserView.as_view(), name='register_ecco'),
    path("select_production/", views.SelectCategoryView.as_view(), name='sellect_production'),
    path("select_cat/", views.SelectCategoryView.as_view(), name='select_cat'),
    path("add_dress/", views.AddDressView.as_view(), name='add_dress'),
    path("add_equ/", views.AddEquipmentView.as_view(), name='add_equ'),
    path("add_machin/", views.AddMachinView.as_view(), name='add_machin'),
    path("list_production/", views.ListProductionView.as_view(), name='list_production'),
    path("detail_production/<int:id>/", views.DetailProductionView.as_view(), name='detail_production'),
    path("create_ticket/", views.OpenTicketView.as_view(), name='create_ticket'),
    path("show_tickets/", views.ShowTicket.as_view(), name='show_tickets'),
    path("detail_ticket/<int:id>/", views.DetailTicket.as_view(), name='detail_ticket'),
    path("reply_ticket/<int:id>/", views.ReplyTicketView.as_view(), name='reply_ticket'),
]

apps/store/urls.py
from django.urls import path
from . import views


app_name='store'
urlpatterns = [
    path('', views.StoreLoginView.as_view(), name='login'),
    path('register/', views.StoreRegisterView.as_view(), name='register'),
    path('register/phone_register/', views.phone_register, name='phone_register'),
    path('register/phone_verify/', views.phone_verify, name='phone_verify'),
    path('register/personal-info/', views.StoreRegisterView.as_view(), name='personal-info'),
    path('register/commer-info/', views.StoreRegisterView.as_view(), name='commer-info'),
    path('dashboard/', views.StoreDashboardView.as_view(), name='dashboard'),
    path('logout/', views.StoreLogoutView.as_view(), name='logout'),
    path('profile/', views.StoreProfileView.as_view(), name='profile'),
    path('update_profile/', views.StoreUpdateProfileView.as_view(), name='update_profile'),
    path('change_password/', views.ChangePasswordView.as_view(), name='change_password'),
]

cheestore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.seller.urls', namespace='seller')),
    path('', include('apps.agent.urls', namespace='agent')),
    path('accounts/', include('apps.accounts.urls', namespace= 'accounts')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/seller/forms.py
from django import forms
from .models import SellerUser
from apps.accounts.models import CustomUser
from django.core.exceptions import ValidationError



class UserRegisterForm(forms.ModelForm):
    password1 = forms.CharField(label='رمز عبور',widget=forms.PasswordInput)
    password2 = forms.CharField(label='تکرار رمز عبور',widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ('name', 'family', 'phone_number', 'national_code', 'email', 'password1', 'password2')


    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("رمز عبور مطابقت ندارد")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class SellerRegisterForm(forms.ModelForm):
    birthdate = forms.DateField(label='تاریخ تولد', required=False,
                                widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'تاریخ تولد خود را وارد کنید', 'type':'date'}),
                                error_messages={'required':'این فیلد الزامی است'}
                                )

    class Meta:
        model = SellerUser
        fields = ['img_profile','gender','birthdate', 'img_national_card','address']

#==================================================================================================================================================

class SellerLoginForm(forms.ModelForm):
    phone_number = forms.CharField(label="تلفن همراه",
                                   widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'شماره تلفن همراه خود را وارد کنید'}),
                                   error_messages={'required':'این فیلد الزامی است'}
                                   )
    password = forms.CharField(label="رمز عبور",
                                   widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'رمز عبور را وارد کنید'}),
                                   error_messages={'required':'این فیلد الزامی است'}
                                   )

    class Meta:
        model = SellerUser
        fields=['phone_number', 'password']


    

#================================================================================================================================
class UserProfileForm(forms.ModelForm):

    class Meta:
        model = CustomUser
        fields = ('name', 'family', 'phone_number', 'national_code', 'email')




#================================================================================================================================
# class PhoneRegisterForm(forms.ModelForm):

#     class Meta:
#         model = SellerUser
#         fields = ('phone_number',)
#         widgets={
#             'phone_number':forms.TextInput(attrs={'placeholder':'تلفن همراه خود را وارد کنید','class':'form-control'})}


class PhoneRegisterForm(forms.Form):
    phone_number = forms.CharField(label="", help_text="مثال: 09123456789",
                                    # widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'شماره تلفن همراه خود را وارد کنید'}),
                                    # error_messages={'required':'این فیلد الزامی است'},
                                    # validators=[RegexValidator(regex='^(09)\d{9}$',message="تلفن همراه می بایست 11رقم و فقط شامل عدد باشد  ",)]
                                    ) 

apps/seller/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import SellerUser
from .forms import SellerRegisterForm, UserRegisterForm, SellerLoginForm, PhoneRegisterForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views import View
import random


#=================================SellerRegister===================================================

class SellerRegisterView(View):
    # def dispatch(self, request, *args, **kwargs):
    #     if request.user.is_authenticated:
    #         return redirect('seller:login')
    #     return super().dispatch(request, *args, **kwargs)
        
    def get(self,request, *args, **kwargs):
        user_form = UserRegisterForm()
        seller_form = SellerRegisterForm()
        return render(request, 'seller/register.html', {'user_form': user_form, 'seller_form':seller_form})

    def post(self,request,*args, **kwargs):
        user_form = UserRegisterForm(request.POST)
        seller_form = SellerRegisterForm(request.POST, request.FILES)
        if user_form.is_valid() and seller_form.is_valid():
            custom_user = user_form.save()
            seller = seller_form.save(commit=False)
            seller.user = custom_user
            seller.save()
            messages.success(request,'ثبت نام با موفقیت انجام شد')
            return redirect('seller:login')
        else:
            messages.error(request, 'اطلاعات وارد شده معتبر نمی باشد')
            return render(request, 'seller/register.html', {'user_form': user_form, 'seller_form': seller_form})

#=================================SellerLogin===================================================

class SellerLoginView(View):
    # def dispatch(self, request, *args, **kwargs):
    #     if request.user.is_authenticated:
    #         return redirect('seller:login')
    #     return super().dispatch(request, *args, **kwargs)
    
    def get(self,request, *args, **kwargs):
        form = SellerLoginForm()
        return render(request,'seller/login.html', {'form':form})

    def post(self,request,*args, **kwargs):
        form = SellerLoginForm(request.POST)
        if form.is_valid():
            username=form.cleaned_data.get('phone_number')
            password=form.cleaned_data.get('password')
            user = authenticate(
            username=username,
            password=password
            )
            if user is not None:
                messages.success(request, 'ورود شما با موفقیت انجام شد')
                login(request,user)
                next_url=request.GET.get('next')
                if next_url is not None:
                    return redirect(next_url)
                else:
                    return redirect('seller:dashboard')
            else:
                messages.warning(request,'کاربر با این مشخصات یافت نشد')
                return render(request, 'seller/login.html', {'form':form})
        else:
            messages.error(request, 'اطلاعات وارد شده معتبر نمی باشد')
            return render(request, 'seller/login.html', {'form':form})

#============================SellerLogout========================================================

class SellerLogoutView(View):    
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('seller:login')
        return super().dispatch(request, *args, **kwargs)
    
    def get(self,request, *args, **kwargs):
        logout(request)
        messages.warning(request, 'خروج شما با موفقیت انجام شد')
        return redirect('seller:login')

#=============================SellerProfile=======================================================
from apps.accounts.models import CustomUser

class SellerProfileView(View):
    def get(self,request,*args, **kwargs):
        user=request.user
        seller =SellerUser.objects.get(user=user)
        return render(request, 'seller/profile.html', {'user':user, 'seller':seller})


#=============================SellerUpdateProfile=======================================================

class SellerUpdateProfileView(View):
    def get(self,request,*args, **kwargs):
        user_form = UserProfileForm(instance=request.user)
        seller_form = SellerRegisterForm(instance=request.user.selleruser)
        return render(request, 'seller/update_profile.html',{'user_form':user_form, 'seller_form':seller_form})

    def post(self,request,*args, **kwargs):
        user_form = UserProfileForm(request.POST, instance=request.user)
        seller_form = SellerRegisterForm(request.POST, request.FILES, instance=request.user.selleruser)
        if user_form.is_valid() and seller_form.is_valid():
            user_form.save()
            seller_form.save()
            messages.success(request, 'پروفایل شما با موفقیت ویرایش شد')
            return redirect('seller:dashboard')
        else:
            messages.error(request, 'اطلاعات وارد شده معتبر نمی باشد')
            return render(request, 'seller/update_profile.html', {'user_form': user_form, 'seller_form': seller_form})

#=============================ChangePassword=======================================================


from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin

class ChangePasswordView(SuccessMessageMixin, PasswordChangeView):
    template_name = 'seller/change_password.html'
    success_message = "رمز عبور با موفقیت تغییر کرد"
    success_url = reverse_lazy('seller:dashboard')

#=============================SellerDashboard=======================================================

class SellerDashboardView(View):
    def get(self,request,*args, **kwargs):
        return render(request, 'seller/dashboard.html',{'form':'form'})

    def post(self,request,*args, **kwargs):
        pass


#============================PhoneRegister========================================================
# def codeGenerate():
#     return random.randint(1000,9999)
from django_otp.oath import totp

secret_key = b'12345678901234567890'
code = totp(key=secret_key, step=30, digits=4)

def phone_register(request):
    form = PhoneRegisterForm()
    if request.method == 'POST':
        form = PhoneRegisterForm(request.POST)
        if form.is_valid():
            register_phone = form.cleaned_data['phone_number']
        print(register_phone, ": " ,code)
        return redirect('seller:phone_verify')
    return render(request, 'seller/phone_register.html', {'form':form})

#============================PhoneVerify========================================================

def phone_verify(request):
    print("code", code)
    # if request.method =='POST':
    verify_code = request.GET.get('phone_verify')
    if verify_code == str(code):
        print(verify_code, "You send to the next page")
        return redirect('seller:register')
    return render(request, 'seller/phone_verify.html',{'code':code})


#===================================================================================

templates/seller/add_dress.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}

{% block title %}افزودن محصول{% endblock title %}


{% block content %}
<h1 class="text-center text-primary">افزودن محصول</h1>
<div class="row justify-content-md-center form-group">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
 
        {{ dress_form | crispy }}

    
        <input type="submit" value="اضافه کن" class="btn btn-success">
    </form>
</div>
{% endblock content %}

templates/seller/add_equ.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}

{% block title %}افزودن محصول{% endblock title %}


{% block content %}
<h1 class="text-center text-primary">افزودن محصول</h1>
<div class="row justify-content-md-center form-group">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
 
        {{ equipment_form | crispy }}

    
        <input type="submit" value="اضافه کن" class="btn btn-success">
    </form>
</div>
{% endblock content %}

templates/seller/add_machin.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}

{% block title %}افزودن محصول{% endblock title %}


{% block content %}
<h1 class="text-center text-primary">افزودن محصول</h1>
<div class="row justify-content-md-center form-group">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
 
        {{ machin_form | crispy }}

    
        <input type="submit" value="اضافه کن" class="btn btn-success">
    </form>
</div>
{% endblock content %}

templates/seller/change_password.html
{% extends "main.html" %}

{% block titile %}تغییر رمز عبور{% endblock titile %}

{% block content %}

    {% if form.errors %}
                {% for error in form.errors %}
                    <strong>{{ error }}</strong>
                {% endfor %}
    {% endif %}


        <form action="{% url 'seller:change_password' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="old_password">رمز عبور قدیمی</label>
                <input type="password" name="old_password" class="form-control" required/>
            </div>
            <div class="form-group">
                <label for="new_password1">رمز عور جدید</label>
                <input type="password" name="new_password1" class="form-control" required/>
            </div>
            <div class="form-group">
                <label for="new_password2">تکرار رمز عبور جدید</label>
                <input type="password" name="new_password2" required class="form-control"/>
            </div>
            <div class="mt-1">
                <button type="submit" class="btn btn-success">تایید</button>
            </div>
        </form>

{% endblock content %}

templates/seller/detail_production.html
{% extends 'main.html' %}

{% block title %}جزئیات کالا{% endblock title %}


{% block content %}
<h1 class="text-center text-primary">جزئیات کالا</h1>
<div class="row justify-content-md-center form-group">

    <ul>
        <li>نام کالا: {{dress}}</li>
        <li>دسته بندی: {{dress.first_category}}</li>
        <li>تعداد: {{dress.numbers}}</li>
        <li>سایز : {{dress.size}}</li>
        <li>جنس: {{dress.nature}}</li>
        <li>رنگبندی: {% for color in dress.colors.all %}{{ color }},{% endfor %}</li>
        <li>قیمت: {{dress.price}}</li>
        <li>توضیحات: {{dress.description}}</li>
        <li>تصویر کالا: {{dress.image}}</li>
        <li>ویدئوی کالا: {{dress.videofile}}</li>
        <li>موجودی: {{dress.stock}}</li>
    </ul>


</div>
{% endblock content %}

templates/seller/list_productions.html
{% extends 'main.html' %}

{% block title %}انبار{% endblock title %}


{% block content %}
<h1 class="text-center text-primary">لیست کالاها</h1>
<div class="row justify-content-md-center form-group">
    <ul>

        {% for dress in dresses %}
            <a href="{% url 'seller:detail_production' dress.id %}"><li>{{dress}}</li></a>
        {% endfor %}

    </ul>

</div>
{% endblock content %}

templates/seller/login.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}

{% block title %}صفحه ورود فروشندگان{% endblock title %}




{% block content %}
    <h1 class="text-center text-primary">ورود فروشندگان</h1>
    <div class="row justify-content-md-center m-5">
        <form action="" method="post">
            {% csrf_token %}
            {{ form | crispy }}
            <input type="submit" value="ورود" class='btn btn-success btn-lg'>
        </form>
    </div>
    <div class="m-5">
        <p><a href="/accounts/password_reset/">رمز عبورم را فراموش کرده ام</a></p>
    </div>
    
    
    <div class="m-5">
        <p>هنوز ثبت نام کرده اید؟<a href="{% url 'seller:phone_register' %}">همین حالا ثبت نام کنید</a></p>
        
    </div>
{% endblock content %}

templates/seller/open_ticket.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}

{% block title %}پشتیبانی{% endblock title %}


{% block content %}
<h1 class="text-center text-primary">تیکت پشتیبانی</h1>
<div class="row justify-content-md-center form-group">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form | crispy }}
        <input type="submit" value="ارسال" class="btn btn-success">
    </form>
</div>
{% endblock content %}

templates/seller/phone_register.html
{% extends 'main.html' %}

{% block title %}ثبت تلفن همراه{% endblock title %}ثبت تلفن همراه

{% block content %}
<h1 class="text-center text-primary">ثبت تلفن همراه</h1>
<div class="container">
<div class="row justify-content-center align-items-center">
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <div>
    <input type="submit" class="btn btn-primary mt-3" value="تایید">
    </div>
</form>
</div>
</div>
{% endblock content %}

templates/seller/phone_verify.html
{% extends 'main.html' %}

{% block title %}تایید تلفن همراه{% endblock title %}
{% block content %}

<h3>{{message}}</h3>

<p>لطفا کد ارسال شده را وارد کنید</p>
<form action="" >
    {% csrf_token %}
    <div class="form-group mt-2">
        <label for="phone_verify">کد تایید : </label>
        <input type="number" name="phone_verify" id="phone_verify">
    </div>
    <div class= "mt-2">
        <input type="submit" class="btn btn-primary" value="ارسال">
    </div>
</form>
<div class= "mt-4">
    <p>کدی دریافت نکرده اید؟<a href="#">ارسال مجدد کد</a></p>
    
</div>
<div class= "mt-2">
    <p><a href="">ویرایش شماره تلفن</a></p>
</div>

{{code}}

        
{% endblock content %}

templates/seller/register_ecco.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}

{% block title %}اطلاعات تجاری{% endblock title %}


{% block content %}
<h1 class="text-center text-primary">ثبت نام فروشندگان</h1>
<div class="row justify-content-md-center form-group">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form | crispy }}
        <input type="submit" value="ادامه" class="btn btn-success">
    </form>
</div>
{% endblock content %}

templates/seller/reply_ticket.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}

{% block title %}پاسخ تیکت{% endblock title %}


{% block content %}
<h1 class="text-center text-primary">پاسخ تیکت</h1>
<div class="row justify-content-md-center form-group">


    <ul>
        <li>ادمین: {{reply.admin}}</li>
        <li>پاسخ تیکت: {{reply.reply}}</li>
        <li>کاربر: {{reply.user}}</li>
        <li>زمان پاسخگویی: {{reply.created_at}}</li>

    </ul>

    <hr>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form | crispy }}
        <input type="submit" value="ارسال" class="btn btn-success">
    </form>


</div>
{% endblock content %}

templates/seller/select_category.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}

{% block title %}انتخاب محصول{% endblock title %}


{% block content %}
<h1 class="text-center text-primary">انتخاب کالا</h1>
<div class="row justify-content-md-center form-group">

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form | crispy }}
        <input type="submit" value="انتخاب" class="btn btn-success">
    </form>


</div>
{% endblock content %}